version: '3.8'

services:
  db:
    image: postgres:14
    container_name: nedoma_db
    environment:
      POSTGRES_DB: nedoma_copy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
