version: '3.8'

services:
  db:
    image: postgres:14
    container_name: nedoma_db
    environment:
      POSTGRES_DB: nedoma_copy
      POSTGRES_USER: grigorii
      POSTGRES_PASSWORD: your-password
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
      - ./docker/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./docker/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    command: ["postgres", "-c", "config_file=/var/lib/postgresql/data/postgresql.conf"]
    ports:
      - "5432:5432"

volumes:
  postgres-data:
